# Generated by Django 4.2.29 on 2026-03-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('type', models.CharField(max_length=128)),
                ('status', models.CharField(default='online', max_length=128)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
