# Generated by Django 4.2.29 on 2026-03-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTDatasetUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_records', models.IntegerField(default=0)),
                ('anomalies_detected', models.IntegerField(default=0)),
                ('summary', models.JSONField(default=dict)),
            ],
        ),
    ]
