# Generated by Django 4.2.29 on 2026-03-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('attack_type', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
